### ISSUE TITLE
Unable to add shadcn components

### ISSUE THREAD

**Issue by raw-brt** [midday-ai/v1#18]
Is there a reason why you haven't added a components.json file in the ui package?

For those of you trying to add shadcn components to the ui package, you need to add a components.json as described in the docs. Something like this:

```
{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "new-york",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "tailwind.config.ts",
    "css": "src/globals.css",
    "baseColor": "gray",
    "cssVariables": true,
    "prefix": ""
  },
  "aliases": {
    "components": "@/components",
    "utils": "@/utils"
  }
}
```

Great project, guys. Thank you for sharing it!

**Comment by pontusab** [comment]
oh I'm to use to do it manually! wanna do a PR for this? 🖤

**Comment by 0xVitae** [comment]
Where do you add this?

**Comment by jedimonkey** [comment]
My pr didn't fully fix the issue - but I can't work out how you are bringing in the shadcn components in the format that you have in the repo. Do you add them and then fix the paths?

Is the ts aliases a bun monorepo issue? The IDE seems to know what's going on, but Bun fails. I'd re-open this ticket, as it's not fixed.

**Comment by KyoeiX** [comment]
I had to:
`bun add @radix-ui/react-switch` 

in
`packages/ui` 

Then add the Shadcn Switch component manually, updating the references in package.json:
```
"exports": {
    "./globals.css": "./src/globals.css",
    "./cn": "./src/utils/cn.ts",
    "./button": "./src/components/button.tsx",
    "./input": "./src/components/input.tsx",
    "./tooltip": "./src/components/tooltip.tsx",
    "./dialog": "./src/components/dialog.tsx",
    "./icons": "./src/components/icons.tsx",
    "./switch": "./src/components/switch.tsx",
    "./tailwind.config": "./tailwind.config.ts",
    "./postcss": "./postcss.config.js"
  },
```

**Comment by 0xVitae** [comment]
this is broken still
