### ISSUE TITLE
No output directory found

### ISSUE THREAD

**Issue by northrn** [midday-ai/v1#23]
Currently receiving this error when trying to deploy using deploy button in the repo:

`Error: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings.`

Tried overriding output directory settings in Vercel but with no luck.

**Comment by lluisinthedesert** [comment]
Same issue.

**Comment by mu-ct** [comment]
In your Vercel dashboard, click on the project, go to Settings and in Build & Development Settings click on Override for Output Directory and put '.' there (just the full stop, without the quotation marks). Then Save, go to Deployments and Redeploy

**Comment by abdokouta** [comment]
@mu-ct i have try it and getting 404, [,](https://create-v1-mu.vercel.app/) and below is my deployment config

<img width="1800" alt="image" src="https://github.com/user-attachments/assets/7bf63fad-6f5c-4d62-9df7-32aabc0f6bf9">

**Comment by northrn** [comment]
> In your Vercel dashboard, click on the project, go to Settings and in Build & Development Settings click on Override for Output Directory and put '.' there (just the full stop, without the quotation marks). Then Save, go to Deployments and Redeploy

Same as above, that will get you a deployment, but then you just have a 404 at the destination.

**Comment by nuchtoskazat** [comment]
same

**Comment by pontusab** [comment]
fix incoming!

**Comment by alecdewitz** [comment]
![Screenshot 2024-09-05 at 21 55 24](https://github.com/user-attachments/assets/5c56d6d9-41bc-4cf8-963a-66fc0ff05d8b)
Fixed this by changing the output directory to `apps/web/.next` as shown above

**Comment by abdokouta** [comment]
@alecdewitz same issue 404

<img width="1800" alt="image" src="https://github.com/user-attachments/assets/5b202a23-c3a9-4e75-99df-da9fcd625080">

**Comment by abdokouta** [comment]
@alecdewitz it's fixed after changing the Framework Preset to `nextjs`

**Comment by pontusab** [comment]
<img width="930" alt="Screenshot 2024-09-06 at 12 28 53" src="https://github.com/user-attachments/assets/38b39c8f-0432-465d-a6e3-3d03cb735c1e">

1. Select Framework and Preset to nextjs
2. Add `turbo run build --filter=@v1/app` or ` `turbo run build --filter=@v1/web` depending on application
3. Make a new deployment by a git push (change something) for the build settings to take effect

Adding this to the documentation, unfortunately I can't get the deploy with Vercel button work with this!

**Comment by mihau12** [comment]
Hey, thanks as lot for your work! 

Unfortunately the solution leads to "The file "/vercel/path0/.next/routes-manifest.json" couldn't be found. This is often caused by a misconfiguration in your project."

**Comment by northrn** [comment]
> Hey, thanks as lot for your work!
> 
> Unfortunately the solution leads to "The file "/vercel/path0/.next/routes-manifest.json" couldn't be found. This is often caused by a misconfiguration in your project."

Yep same issue for me. @pontusab

**Comment by erquhart** [comment]
@pontusab looks like the vercel deploy has diverged quite a bit from real world initialization (and it's broken) - might be worth dropping it. Lost a good amount of time trying to get it working before scrapping and just following the readme.

**Comment by hamilton-lima** [comment]
With this approach we would need a separated project for each application right? as the build command is filtering for `@v1/app` only. is there a way to setup the build to deploy all: api and app and web with a single project?

**Comment by PlexusTools** [comment]
Getting this same issue still @pontusab any update?
