### ISSUE TITLE
Action error: (0 , _v1_logger__WEBPACK_IMPORTED_MODULE_1__.logger) is not a function

### ISSUE THREAD

**Issue by DiogoDuart3** [midday-ai/v1#32]
Error when calling server action

![image](https://github.com/user-attachments/assets/b3ed8abc-861e-4df8-a2d1-ef59d1ed6fc3)

**Comment by DiogoDuart3** [comment]
The problem comes from here:

![image](https://github.com/user-attachments/assets/cbbfa504-a1e7-4521-a82c-f8cd253f581b)

**Comment by pontusab** [comment]
Fixed, thanks for reporting!
