### ISSUE TITLE
Why two Next.js apps?

### ISSUE THREAD

**Issue by mohsen1** [midday-ai/v1#35]
I'm curious to learn why you decided to have two Next.js apps (`app/app` and `app/web`) and also an API package? Why one Next.js app would not be sufficient in your case?

**Comment by pontusab** [comment]
It's a common structure to have when your app is growing and you want to have things separated while still having all your packages etc in the same repo, api in this case is everything supabase related, also you can self-host that if you want. I usually have my marketing website att example.com and my product on app.example.com and I like it a lot.

Alos if you where about to add a mobile app using react-native with expo you can just have it under /apps and have everything in one place!

Let me know if that make sense!

**Comment by pontusab** [comment]
I'm closing this for now, let me know if you want more insights on this!
