### ISSUE TITLE
Fix header UI button alignment

### ISSUE THREAD

**Issue by ChrisAbdo** [midday-ai/v1#41]
Super basic issue but the buttons in the header are not aligned. Simple fix is adding "items-center" utility to `<ul className="flex gap-4">` in header.tsx

pre: 
 `<ul className="flex gap-4">` 
<img width="877" alt="image" src="https://github.com/user-attachments/assets/73334d00-1426-420b-81c3-9922e1caded0">

post: 
 `<ul className="flex items-center gap-4">` 
<img width="875" alt="image" src="https://github.com/user-attachments/assets/65428b28-06c2-45b3-b539-4cfd88969de3">

**Comment by pontusab** [comment]
Fixed, thank you!
