### ISSUE TITLE
Missing Deno Definitions in send-email Function When Using Bun

### ISSUE THREAD

**Issue by sleda** [midday-ai/v1#51]
Hello,

First of all, thank you for this great starter kit!

Issue Description:

In the project, specifically in apps/api/supabase/functions/send-email/index.ts, Deno-specific APIs such as Deno.env.get and Deno.serve are being used. However, the project uses Bun as the runtime, and there are no Deno definitions or configurations present.

This causes errors when trying to run the send-email function because Bun does not support Deno's APIs directly.

Error Message:
```
Cannot find name 'Deno'.ts(2304)
⚠ Error(TS2304) |
Cannot find name 'Deno'.
any
```

Code Snippet:
```
import { WelcomeEmail } from "@v1/email/emails/welcome";
import React from "react";
import { render } from "react-email/components";
import { Resend } from "resend";
import { Webhook } from "standardwebhooks";

const resend = new Resend(Deno.env.get("RESEND_API_KEY") as string);
const hookSecret = Deno.env.get("SEND_EMAIL_HOOK_SECRET") as string;

Deno.serve(async (req) => {
  // ......
});

```

**Comment by giulioco** [comment]
Also had this issue by the way, fixed by adding 

```json 
  "deno.enable": true,
  "deno.unstable": true,
```

to `.vscode/settings.json`
