### ISSUE TITLE
missing .env.example, I think!

### ISSUE THREAD

**Issue by mahavatara** [midday-ai/v1#7]
Hey,

I had no idea about bun, but anyway found it, followed the README and, no signs of any .example anywhere

**Comment by northrn** [comment]
> Hey,
> 
> I had no idea about bun, but anyway found it, followed the README and, no signs of any .example anywhere

You have to 'cd' into /apps and then /app

**Comment by serkandyck** [comment]
> > Hey,
> > I had no idea about bun, but anyway found it, followed the README and, no signs of any .example anywhere
> 
> You have to 'cd' into /apps and then /app. It's not located in the project root. I made the same mistake.

I think you need to set in all folders app, api, web

**Comment by mahavatara** [comment]
> > > Hey,
> > > I had no idea about bun, but anyway found it, followed the README and, no signs of any .example anywhere
> > 
> > 
> > You have to 'cd' into /apps and then /app. It's not located in the project root. I made the same mistake.
> 
> I think you need to set in all folders app, api, web

indeed. I did an ls -lrt before posting here but apparently I need the -a too :)
