### ISSUE TITLE
'Bun dev' failing

### ISSUE THREAD

**Issue by northrn** [midday-ai/v1#8]
`matthew@Matthews-MacBook-Pro-2 v1 % bun dev
$ turbo dev --parallel
turbo 2.1.1

• Packages in scope: @v1/analytics, @v1/api, @v1/app, @v1/email, @v1/jobs, @v1/kv, @v1/logger, @v1/supabase, @v1/typescript, @v1/ui, @v1/web
• Running dev in 11 packages
• Remote caching disabled
@v1/api:dev: cache bypass, force executing 23765c3e769ef9b1
@v1/web:dev: cache bypass, force executing 67c27a30208b3233
@v1/app:dev: cache bypass, force executing 542dfb97ae97bb3f
@v1/email:dev: cache bypass, force executing 9e58771a5faa85a2
@v1/api:dev: $ supabase start
@v1/web:dev: $ next dev -p 3001
@v1/app:dev: $ next dev -p 3000
@v1/email:dev: $ email dev -p 3003
**@v1/api:dev: Error evaluating "env(GOOGLE_CLIENT_ID)": environment variable GOOGLE_CLIENT_ID is unset.**
@v1/api:dev: Try rerunning the command with --debug to troubleshoot the error.
@v1/api:dev: error: script "dev" exited with code 1
@v1/api:dev: ERROR: command finished with error: command (/Users/northrn/Documents/saas/v1/apps/api) /Users/northrn/.nvm/versions/node/v20.13.1/bin/bun run dev exited (1)
@v1/api#dev: command (/Users/northrn/Documents/saas/v1/apps/api) /Users/northrn/.nvm/versions/node/v20.13.1/bin/bun run dev exited (1)

 Tasks:    0 successful, 4 total
Cached:    0 cached, 4 total
  Time:    320ms 
Failed:    @v1/api#dev

 ERROR  run failed: command  exited (1)`

This is the error I get when trying to run **Bun dev**. I have clearly set my GOOGLE_CLIENT_ID env variable, so I have no idea what's causing this.

**Comment by serkandyck** [comment]
rename all .env.example to .env and fill all with the keys

**Comment by northrn** [comment]
> rename all .env.example to .env and fill all with the keys

Yes figured it out just now. Stupid on my part! Thank you!
